#pragma once
CONST DWORD GAME_BASE_OFFSET = 0x2C5E0C; //游戏LawnAPP* 实例偏移 [BaseAddress+GAME_BASE_OFFSET]
CONST DWORD GAME_BOARD_OFFSET = 0x730; //游戏Board*板 实例偏移 [[BaseAddress+GAME_BASE_OFFSET]+GAME_BOARD_OFFSET]
CONST DWORD GAME_SUN_OFFSET = 0x384; //阳光 偏移  [[[BaseAddress+GAME_BASE_OFFSET]+GAME_BOARD_OFFSET]+GAME_SUN_OFFSET]
CONST DWORD GAME_CARD_OFFSET = 0x14C; //卡槽 实例偏移  [[[BaseAddress+GAME_BASE_OFFSET]+GAME_BOARD_OFFSET]+GAME_CARD_OFFSET]
CONST DWORD GAME_CARD_NUMBER_OFFSET = 0x24; //卡槽个数 偏移  [[[[BaseAddress+GAME_BASE_OFFSET]+GAME_BOARD_OFFSET]+GAME_CARD_OFFSET]+GAME_CARD_NUMBER_OFFSET]
CONST DWORD GAME_CARD_ID_OFFSET = 0x2C; //卡槽ID 偏移  [[[[BaseAddress+GAME_BASE_OFFSET]+GAME_BOARD_OFFSET]+GAME_CARD_OFFSET]+GAME_CARD_ID_OFFSET]
CONST DWORD GAME_CARD_SIZE = 0x38; //卡槽类大小
CONST DWORD GAME_CARD_ID_START_OFFSET = 0x1C; //卡槽ID特殊起始点 偏移 [[[[[BaseAddress+GAME_BASE_OFFSET]+GAME_BOARD_OFFSET]+GAME_CARD_OFFSET]+GAME_CARD_ID_OFFSET]+GAME_CARD_ID_START_OFFSET]
CONST DWORD GAME_PLANT_SUB_SUN_OFFSET = 0x9FC29;//种植植物阳光减少 偏移 [BaseAddress+GAME_PLANT_SUB_SUN_OFFSET]
CONST CHAR* GAME_PLANT_SUB_SUN_PATCH_OPCODE = "\x90\x90\x90\x90\x90\x90"; //种植植物阳光减少_阳光不减少 操作码
CONST CHAR* GAME_PLANT_SUB_SUN_ORIGINAL_OPCODE = "\x29\xBE\x84\x03\x00\x00"; //种植植物阳光减少_原码 操作码
CONST DWORD GAME_PLANT_NO_CD_OFFSET = 0x1025C9; //重新种植更新当前冷却 偏移 [BaseAddress+GAME_PLANT_NO_CD_OFFSET]
CONST CHAR* GAME_CARD_NO_CD_PATCH_OPCODE = "\xC7\x42\x24\x00\x00\x00\x00\x90\x90\x90"; //重新种植更新当前冷却_重置冷却设为0 操作码
CONST CHAR* GAME_CARD_NO_CD_ORIGINAL_OPCODE = "\x89\x42\x24\xC7\x42\x20\x00\x00\x00\x00"; //重新种植更新当前冷却_原码 操作码
CONST DWORD GAME_PLANT_IGNORE_CD_OFFSET = 0x10288D; //判断冷却是否结束 偏移 [BaseAddress+GAME_PLANT_IGNORE_CD_OFFSET]
CONST CHAR* GAME_CARD_IGNORE_CD_PATCH_OPCODE = "\x90\x90"; //判断冷却是否结束_不判断 操作码
CONST CHAR* GAME_CARD_IGNORE_CD_ORIGINAL_OPCODE = "\x39\x08"; //判断冷却是否结束_原码 操作码